version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: productservice_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - productservice_mongodb_data:/data/db
    restart: unless-stopped

volumes:
  productservice_mongodb_data: